### ISSUE TITLE
Failed assertion: line 206 pos 12: '_overlay != null': is not true.

### ISSUE THREAD

**Issue by Dumoulin-Lander** [marcelogil/el_tooltip#26]
Since updating our version to 2.2.0 one of our tests is failing:

```
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 206 pos 12: '_overlay != null':
is not true.

When the exception was thrown, this was the stack:
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:206:12)
#3      _ElTooltipState.dispose.<anonymous closure> (package:el_tooltip/el_tooltip.dart:124:53)
#12     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:197:32)
#13     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1380:24)
#14     _runWidget (package:flutter/src/widgets/binding.dart:1466:7)
#15     runApp (package:flutter/src/widgets/binding.dart:1399:3)
#16     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1039:7)
2
<asynchronous suspension>
(elided 11 frames from class _AssertionError, dart:async, and package:stack_trace)
```

This issue does not exist/happen when downgrading our version to 2.0.0 again.

**Comment by marcelogil** [comment]
@Dumoulin-Lander , can you try again with the new version 2.2.1?
Thanks!

**Comment by Dumoulin-Lander** [comment]
> @Dumoulin-Lander , can you try again with the new version 2.2.1?
> Thanks!

That seems to have done the trick! Thanks!

**Comment by marcelogil** [comment]
I'm glad it worked. thanks for letting me know.
